"use client";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  X, 
  Sparkles, 
  Brain, 
  Clock, 
  Target, 
  Layers, 
  ChevronRight, 
  Loader2, 
  CheckCircle2, 
  RefreshCw, 
  FileText,
  Save
} from "lucide-react";

interface AIStoryGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
  onUse: (data: any) => void;
}

const CATEGORIES = ["Psychology", "Business", "Philosophy", "Cinema", "Power & Influence"];
const STYLES = ["Documentary", "Cinematic", "Conversational", "Dramatic"];
const DURATIONS = ["5 min", "10 min", "15 min", "20 min"];
const FOCUS_AREAS = ["Vocabulary", "Grammar", "Listening", "Speaking confidence"];

export default function AIStoryGenerator({ isOpen, onClose, onUse }: AIStoryGeneratorProps) {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    topic: "",
    category: "Psychology",
    style: "Cinematic",
    difficulty: "Intermediate",
    duration: "10 min",
    focus: "Vocabulary"
  });

  const [loadingMessage, setLoadingMessage] = useState("");
  const [generatedContent, setGeneratedContent] = useState<any>(null);

  const loadingMessages = [
    "Analyzing topic and research papers...",
    "Drafting a cinematic narrative structure...",
    "Injecting psychological hooks...",
    "Highlighting key vocabulary for {difficulty} level...",
    "Generating context-aware quiz questions...",
    "Finalizing the script for audio production..."
  ];

  const handleGenerate = async () => {
    setStep(2);
    let msgIndex = 0;
    
    // Simulate generation process with messages
    const interval = setInterval(() => {
      setLoadingMessage(loadingMessages[msgIndex].replace("{difficulty}", formData.difficulty));
      msgIndex++;
      if (msgIndex >= loadingMessages.length) clearInterval(interval);
    }, 1500);

    // Mocking Claude API Call
    setTimeout(() => {
      setGeneratedContent({
        title: `AI Generated: ${formData.topic}`,
        description: `A ${formData.style.toLowerCase()} exploration of ${formData.topic}, focusing on ${formData.focus.toLowerCase()} and practical application.`,
        transcript: `[NARRATOR]: Imagine a world where ${formData.topic} isn't just a concept, but a living, breathing reality...\n\n(Music swells with a ${formData.style.toLowerCase()} undertone)\n\nIn this story, we explore how ${formData.difficulty.toLowerCase()} learners can master the nuances of English through the lens of ${formData.category.toLowerCase()}.\n\n"The biggest challenge," says the protagonist, "isn't the vocabulary, it's the mindset."\n\nThis is a placeholder for a 500-1000 word script generated by Claude AI based on the user's specific inputs for topic, style, and learning focus.`,
        tags: `${formData.topic.toLowerCase()}, ai-generated, ${formData.category.toLowerCase()}`,
        xp: 350,
        quizzes: [
          { question: "What is the primary focus of this narrative?", options: ["Emotional hooks", "Mindset", "Grammar", "Technical data"], answer: 1, checked: true },
          { question: "Which term was emphasized for the protagonist?", options: ["Challenge", "Vocabulary", "Mindset", "English"], answer: 2, checked: true },
          { question: "How does the narrator describe the world?", options: ["A concept", "A living reality", "A dream", "A struggle"], answer: 1, checked: true }
        ]
      });
      setStep(3);
    }, 9000);
  };

  const reset = () => {
    setStep(1);
    setGeneratedContent(null);
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[250] flex items-center justify-center p-4">
        {/* Backdrop */}
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-black/90 backdrop-blur-xl"
        />

        {/* Modal */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.9, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.9, y: 20 }}
          className="relative w-full max-w-4xl bg-[#1a1a1a] border border-white/10 rounded-[48px] shadow-2xl flex flex-col overflow-hidden max-h-[90vh]"
        >
          {/* Header */}
          <div className="p-8 border-b border-white/5 flex items-center justify-between bg-white/[0.01]">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-2xl bg-amber-500/10 flex items-center justify-center">
                <Sparkles size={24} className="text-amber-500" />
              </div>
              <div>
                <h3 className="text-2xl font-display font-black text-white">AI Story Architect</h3>
                <p className="text-[10px] font-bold text-white/20 uppercase tracking-widest mt-1">Powered by Claude 3.5 Sonnet</p>
              </div>
            </div>
            <button onClick={onClose} className="p-3 rounded-2xl hover:bg-white/5 text-white/20 hover:text-white transition-all">
              <X size={24} />
            </button>
          </div>

          <div className="flex-1 overflow-y-auto p-10 custom-scrollbar">
            {step === 1 && (
              <div className="space-y-10">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                  <div className="space-y-6">
                    <div className="space-y-2">
                      <label className="text-[10px] uppercase font-bold tracking-widest text-white/30 ml-4">Main Topic / Theme</label>
                      <textarea 
                        value={formData.topic}
                        onChange={(e) => setFormData({ ...formData, topic: e.target.value })}
                        rows={3}
                        placeholder="e.g. The psychology of procrastination and the 'Flow State'..."
                        className="w-full bg-white/5 border border-white/5 rounded-3xl py-6 px-8 text-white font-bold focus:outline-none focus:border-amber-500/50 transition-all resize-none text-lg"
                      />
                    </div>

                    <div className="space-y-2">
                      <label className="text-[10px] uppercase font-bold tracking-widest text-white/30 ml-4">Category</label>
                      <div className="grid grid-cols-2 gap-3">
                        {CATEGORIES.map(c => (
                          <button
                            key={c}
                            onClick={() => setFormData({ ...formData, category: c })}
                            className={`py-3 px-4 rounded-xl text-xs font-bold transition-all border ${
                              formData.category === c ? 'bg-amber-500 border-amber-500 text-black' : 'bg-white/5 border-white/5 text-white/40 hover:bg-white/10'
                            }`}
                          >
                            {c}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>

                  <div className="space-y-8">
                    <div className="grid grid-cols-2 gap-6">
                      <div className="space-y-2">
                        <label className="text-[10px] uppercase font-bold tracking-widest text-white/30 ml-4 flex items-center gap-2"><Target size={12} /> Narrative Style</label>
                        <select 
                          value={formData.style}
                          onChange={(e) => setFormData({ ...formData, style: e.target.value })}
                          className="w-full bg-white/5 border border-white/5 rounded-2xl py-4 px-6 text-sm font-bold text-white/60 focus:outline-none appearance-none"
                        >
                          {STYLES.map(s => <option key={s} value={s}>{s}</option>)}
                        </select>
                      </div>
                      <div className="space-y-2">
                        <label className="text-[10px] uppercase font-bold tracking-widest text-white/30 ml-4 flex items-center gap-2"><Clock size={12} /> Target Length</label>
                        <select 
                          value={formData.duration}
                          onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
                          className="w-full bg-white/5 border border-white/5 rounded-2xl py-4 px-6 text-sm font-bold text-white/60 focus:outline-none appearance-none"
                        >
                          {DURATIONS.map(d => <option key={d} value={d}>{d}</option>)}
                        </select>
                      </div>
                    </div>

                    <div className="space-y-2">
                      <label className="text-[10px] uppercase font-bold tracking-widest text-white/30 ml-4 flex items-center gap-2"><Layers size={12} /> Difficulty Level</label>
                      <div className="grid grid-cols-3 gap-2">
                        {["Beginner", "Intermediate", "Advanced"].map(lvl => (
                          <button
                            key={lvl}
                            onClick={() => setFormData({ ...formData, difficulty: lvl })}
                            className={`py-3 rounded-xl text-[10px] font-bold uppercase tracking-widest border transition-all ${
                              formData.difficulty === lvl ? 'bg-blue-500 border-blue-500 text-white' : 'bg-white/5 border-white/5 text-white/40 hover:bg-white/10'
                            }`}
                          >
                            {lvl}
                          </button>
                        ))}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <label className="text-[10px] uppercase font-bold tracking-widest text-white/30 ml-4 flex items-center gap-2"><Brain size={12} /> Learning Focus</label>
                      <div className="flex flex-wrap gap-2">
                        {FOCUS_AREAS.map(f => (
                          <button
                            key={f}
                            onClick={() => setFormData({ ...formData, focus: f })}
                            className={`px-4 py-2 rounded-xl text-[10px] font-bold uppercase tracking-widest transition-all ${
                              formData.focus === f ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/20' : 'bg-white/5 border border-transparent text-white/20 hover:text-white/40'
                            }`}
                          >
                            {f}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>

                <div className="pt-10 flex justify-center">
                  <button 
                    onClick={handleGenerate}
                    disabled={!formData.topic}
                    className="group relative flex items-center gap-4 px-12 py-6 rounded-3xl bg-amber-500 text-black font-display font-black text-xl shadow-glow-amber disabled:opacity-20 disabled:grayscale transition-all hover:scale-105 active:scale-95"
                  >
                    Generate Story Script <ChevronRight size={24} strokeWidth={3} />
                    <div className="absolute -inset-1 rounded-[34px] border-2 border-amber-500 opacity-20 group-hover:scale-110 group-hover:opacity-100 transition-all duration-500" />
                  </button>
                </div>
              </div>
            )}

            {step === 2 && (
              <div className="h-[400px] flex flex-col items-center justify-center space-y-10">
                <div className="relative">
                  <motion.div 
                    animate={{ rotate: 360 }}
                    transition={{ duration: 4, repeat: Infinity, ease: "linear" }}
                    className="w-32 h-32 rounded-full border-4 border-amber-500/10 border-t-amber-500"
                  />
                  <Sparkles className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-amber-500" size={32} />
                </div>
                
                <div className="text-center space-y-4">
                  <AnimatePresence mode="wait">
                    <motion.p 
                      key={loadingMessage}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -10 }}
                      className="text-xl font-bold text-white italic"
                    >
                      {loadingMessage}
                    </motion.p>
                  </AnimatePresence>
                  <div className="w-64 h-1.5 bg-white/5 rounded-full overflow-hidden mx-auto">
                    <motion.div 
                      initial={{ width: 0 }}
                      animate={{ width: "100%" }}
                      transition={{ duration: 9, ease: "easeInOut" }}
                      className="h-full bg-amber-500 shadow-glow-amber"
                    />
                  </div>
                </div>
              </div>
            )}

            {step === 3 && generatedContent && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
                <div className="md:col-span-2 space-y-8">
                  <div className="space-y-2">
                    <label className="text-[10px] uppercase font-bold tracking-widest text-white/30 ml-4 flex items-center gap-2"><FileText size={12} /> Generated Script</label>
                    <textarea 
                      value={generatedContent.transcript}
                      onChange={(e) => setGeneratedContent({ ...generatedContent, transcript: e.target.value })}
                      rows={18}
                      className="w-full bg-black/40 border border-white/10 rounded-[32px] py-8 px-10 text-white font-mono text-sm leading-relaxed focus:outline-none focus:border-amber-500/30 transition-all custom-scrollbar"
                    />
                  </div>
                </div>

                <div className="space-y-8">
                  <div className="space-y-6 p-8 rounded-[40px] bg-white/[0.02] border border-white/5">
                    <h4 className="text-sm font-black text-amber-500 flex items-center gap-2 uppercase tracking-widest">
                      <CheckCircle2 size={16} /> Suggestions
                    </h4>
                    
                    <div className="space-y-4">
                      <div>
                        <div className="text-[10px] font-bold text-white/20 uppercase tracking-widest mb-1">Proposed Title</div>
                        <div className="text-sm font-bold text-white">{generatedContent.title}</div>
                      </div>
                      <div>
                        <div className="text-[10px] font-bold text-white/20 uppercase tracking-widest mb-1">XP Points</div>
                        <div className="text-sm font-black text-amber-500">{generatedContent.xp} XP</div>
                      </div>
                    </div>

                    <div className="w-full h-px bg-white/5" />

                    <div className="space-y-4">
                      <div className="text-[10px] font-bold text-white/20 uppercase tracking-widest mb-3">Quiz Questions</div>
                      {generatedContent.quizzes.map((q: any, i: number) => (
                        <div key={i} className="flex gap-3 items-start">
                          <input 
                            type="checkbox" 
                            checked={q.checked}
                            onChange={() => {
                              const newQuizzes = [...generatedContent.quizzes];
                              newQuizzes[i].checked = !newQuizzes[i].checked;
                              setGeneratedContent({ ...generatedContent, quizzes: newQuizzes });
                            }}
                            className="mt-1 w-4 h-4 rounded border-white/10 bg-white/5 checked:bg-amber-500 accent-amber-500"
                          />
                          <p className="text-[11px] text-white/40 leading-relaxed font-medium">{q.question}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="flex flex-col gap-4">
                    <button 
                      onClick={() => onUse(generatedContent)}
                      className="flex items-center justify-center gap-2 py-5 rounded-3xl bg-amber-500 text-black font-display font-black text-sm shadow-glow-amber hover:scale-105 active:scale-95 transition-all"
                    >
                      <Save size={18} strokeWidth={3} /> Use This Content
                    </button>
                    <button 
                      onClick={reset}
                      className="flex items-center justify-center gap-2 py-4 rounded-3xl bg-white/5 border border-white/5 text-white/40 font-bold text-xs hover:bg-white/10 hover:text-white transition-all"
                    >
                      <RefreshCw size={16} /> Regenerate
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
